name: jupyter-vtk-datawidgets-docs
channels:
  - conda-forge
dependencies:
- python=3.5
- nodejs
- numpy
- sphinx
- nbsphinx
- jupyter_sphinx
- pip:
  - nbsphinx-link
  - pytest_check_links
  - pypandoc
